/* Generated by MyraPad at 12/06/2020 16:23:44 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace ColdBoi.Interface
{
	partial class UI: VerticalStackPanel
	{
		private void BuildUI()
		{
			menuItemOpen = new MenuItem();
			menuItemOpen.Text = "Open ROM...";
			menuItemOpen.Id = "menuItemOpen";

			var menuSeparator1 = new MenuSeparator();

			menuItemQuit = new MenuItem();
			menuItemQuit.Text = "Quit";
			menuItemQuit.Id = "menuItemQuit";

			menuItemFile = new MenuItem();
			menuItemFile.Text = "File";
			menuItemFile.Id = "menuItemFile";
			menuItemFile.Items.Add(menuItemOpen);
			menuItemFile.Items.Add(menuSeparator1);
			menuItemFile.Items.Add(menuItemQuit);

			_mainMenu = new HorizontalMenu();
			_mainMenu.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_mainMenu.AcceptsKeyboardFocus = true;
			_mainMenu.Id = "_mainMenu";
			_mainMenu.Items.Add(menuItemFile);

			
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			AcceptsKeyboardFocus = false;
			Widgets.Add(_mainMenu);
		}

		
		public MenuItem menuItemOpen;
		public MenuItem menuItemQuit;
		public MenuItem menuItemFile;
		public HorizontalMenu _mainMenu;
	}
}